/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlhssv;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ConnectDatabase.ConnectDB;

/**
 *
 * @author Lenovo
 */
public class qlidiem extends javax.swing.JPanel {

    /**
     * Creates new form qlidiem
     */
    public qlidiem() {
        initComponents();
        load_Cbdiem();
        load_diem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection conn = null;
    Map<String, String> sinhvien = new HashMap<>();

    private void load_Cbdiem() {
        try {
            conn = ConnectDB.KetnoiDB();
            String sql = "SELECT * FROM sinhvien";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                cbsv.addItem(rs.getString("hoten"));
                sinhvien.put(rs.getString("hoten"), rs.getString("idsinhvien"));
            }

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcc = new javax.swing.JTextField();
        txtgk = new javax.swing.JTextField();
        txtck = new javax.swing.JTextField();
        btndtb = new javax.swing.JButton();
        txtdtb = new javax.swing.JTextField();
        cbsv = new javax.swing.JComboBox<>();
        cbmon = new javax.swing.JComboBox<>();
        txtdiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdiem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Quan li diem");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nội dung"));

        jLabel2.setText("ID điểm");

        jLabel4.setText("ID sinh viên:");

        jLabel5.setText("ID môn học:");

        jLabel6.setText("Điểm chuyên cần:");

        jLabel7.setText("Điểm giữa kì:");

        jLabel8.setText("Điểm cuối kì");

        btndtb.setText("Điểm trung bình môn");
        btndtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btndtb)
                        .addGap(18, 18, 18)
                        .addComponent(txtdtb, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcc, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtgk)
                            .addComponent(txtck)
                            .addComponent(cbsv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbmon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtdiem))))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cbmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtgk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndtb)
                    .addComponent(txtdtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        tbdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdiem);

        btnThem.setText("Thêm");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jButton4.setText("Xóa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(jButton4))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbdiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdiemMouseClicked
        int i=tbdiem.getSelectedRow();
        DefaultTableModel tb=(DefaultTableModel)tbdiem.getModel();
        txtdiem.setText(tb.getValueAt(i, 0).toString());
        cbsv.setSelectedItem(tb.getValueAt(i, 1).toString());
        cbmon.setSelectedItem(tb.getValueAt(i, 3).toString());
        txtcc.setText(tb.getValueAt(i, 4).toString());
        txtgk.setText(tb.getValueAt(i, 5).toString());
        txtck.setText(tb.getValueAt(i, 6).toString());
        txtdtb.setText(tb.getValueAt(i, 6).toString());
        float diemCC = Float.parseFloat(txtcc.getText());
        float diemGK = Float.parseFloat(txtgk.getText());
        float diemCK = Float.parseFloat(txtck.getText());
        
        float diemTB = (diemCC * 0.1f) + (diemGK * 0.3f) + (diemCK * 0.6f);
        txtdtb.setText(String.valueOf(diemTB));
    }//GEN-LAST:event_tbdiemMouseClicked

    private void btndtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtbActionPerformed
        try {
            float diemCC = Float.parseFloat(txtcc.getText());
            float diemGK = Float.parseFloat(txtgk.getText());
            float diemCK = Float.parseFloat(txtck.getText());

            float diemTB = (diemCC * 0.1f) + (diemGK * 0.3f) + (diemCK * 0.6f);
            txtdtb.setText(String.valueOf(diemTB));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng định dạng điểm!");
        }
    }//GEN-LAST:event_btndtbActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         try {
        String diem = txtdiem.getText().trim();  // Assuming this is the primary key, idgiaovien
        String sv = cbsv.getSelectedItem().toString();
        String mon = cbmon.getSelectedItem().toString();
        String cc = txtcc.getText().trim();
        String gk = txtgk.getText().trim();
        String ck = txtck.getText().trim();
        String dtb = txtdtb.getText().trim();
        String ma = sinhvien.get(sv);

        // Kết nối DB
        con = ConnectDB.KetnoiDB();

        // Sử dụng PreparedStatement để đảm bảo an toàn và chính xác
        String sql = "UPDATE giaovien SET hoten = ?, ngaysinh = ?, gioitinh = ?, diachi = ?, sodienthoai = ?, email = ?, khoa = ? WHERE idgiaovien = ?";
        PreparedStatement st = con.prepareStatement(sql);

        // Set the values for the placeholders
        st.setString(1, diem);
        st.setString(3, sv);
        st.setString(4, mon);
        st.setString(5, cc);
        st.setString(6, gk);
        st.setString(7, ck);
        st.setString(8, dtb);  // Set the idgiaovien as the condition for the WHERE clause

        // Thực hiện câu lệnh cập nhật
        st.executeUpdate();

        // Đóng kết nối
        con.close();

        // Thông báo khi cập nhật thành công
        JOptionPane.showMessageDialog(this, "Sửa thành công!");
        load_diem();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnSuaActionPerformed
 Connection con;
 private void load_diem(){
     try {
        con=ConnectDB.KetnoiDB();
        String sql="Select*From diem";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        String[] tieude={"ID Điểm","ID Sinh Viên","ID Môn học","Điểm chuyên cần","Điểm giữa kì","Điểm cuối kì","Điểm trung bình"};
        DefaultTableModel tb = new DefaultTableModel(tieude,0);
        while(rs.next()){
            Vector v = new Vector();
             v.add(rs.getString("iddiem"));
              v.add(rs.getString("idsinhvien"));
              v.add(rs.getString("idmonhoc"));
              v.add(rs.getString("diem_chuyencan"));
               v.add(rs.getString("diem_giua_ky"));
              v.add(rs.getString("diem_cuoi_ky"));
              v.add(rs.getString("diem_trung_binh"));
              tb.addRow(v);
        }
        tbdiem.setModel(tb);
        con.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btndtb;
    private javax.swing.JComboBox<String> cbmon;
    private javax.swing.JComboBox<String> cbsv;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdiem;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txtck;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txtdtb;
    private javax.swing.JTextField txtgk;
    // End of variables declaration//GEN-END:variables
}
